INSERT INTO person (address, first_name, gender, last_name) VALUES ("P.O. Box 665, 9217 Curae Avenue", "Boris", "Male", "Patterson")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("638-3939 Ultricies St.", "Sacha", "Female", "Vaughn")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Ap #144-5574 Duis St.", "Jerry", "Male", "Sharp")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Ap #350-2656 Nam Road", "Riley", "Female", "Pierce")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Qnl 07 conjunto L", "Jorge", "Male", "Siqueira")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Ap #326-9573 Molestie Street", "Brendan", "Female", "Avila")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Qnl 05 conjunto L, casa 20", "Sandro", "Male", "Siqueira")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("QNN 12 conjunto T, casa 12", "Luísa", "Female", "Oliveira")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Qnl 03 conjunto L, casa 10", "Levi", "Male", "Gonçalves")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("QNN 08 conjunto T", "Mariana", "Female", "Fontes")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Qnl 01 conjunto L", "André", "Male", "Silva")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("QNN 06 conjunto T", "Vivian", "Female", "Prates")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("Qnl 11 conjunto L", "Roberto", "Male", "Guerra")
INSERT INTO person (address, first_name, gender, last_name) VALUES ("QNN 04 conjunto T", "Jussara", "Female", "Calixto")